### ISSUE TITLE
Question/feature: Whitelist option

### ISSUE THREAD

**Issue by lillereven** [tlhackque/BlockCountries#11]
Hey there.

Thanks for this project, it's a great help and has reduced malicious traffic for us. 

Would it be possible to do the inverse, namely whitelist one ore more country/countries and block everything else? 

Thanks,
Martin

**Comment by tlhackque** [comment]
Glad to hear that it has been effective for you.

See -permitonly, which does exactly that. 

P.S. My name isn't "there" :-)
